### ISSUE TITLE
programming sbu via pyupdi fails the first two times

### ISSUE THREAD

**Issue by M-Welsch** [M-Welsch/base-bcu#16]
`update_sbu.py ` switched the uart path to programming

```py
base@bananapi:~$ sudo python3 python.base/sbu_fw_files/update_sbu.py 
base@bananapi:~$ sudo pyupdi -d tiny816 -c /dev/ttyS1 -f /home/base/python.base/sbu_fw_files/BaSe_SBC_wakeup_reason_implementation.hex 
^CDevice is locked. Performing unlock with chip erase.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/pyupdi.py", line 102, in _main
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/nvm.py", line 34, in enter_progmode
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/application.py", line 158, in enter_progmode
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/link.py", line 59, in ldcs
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyupdi", line 11, in <module>
    load_entry_point('pyupdi==0.0.0', 'console_scripts', 'pyupdi')()
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/pyupdi.py", line 105, in _main
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/nvm.py", line 54, in unlock_device
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/application.py", line 121, in unlock
Exception: Failed to chip erase using key
base@bananapi:~$ sudo pyupdi -d tiny816 -c /dev/ttyS1 -f /home/base/python.base/sbu_fw_files/BaSe_SBC_wakeup_reason_implementation.hex 
^CDevice is locked. Performing unlock with chip erase.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/pyupdi.py", line 102, in _main
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/nvm.py", line 34, in enter_progmode
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/application.py", line 158, in enter_progmode
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/link.py", line 60, in ldcs
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/physical.py", line 81, in send
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 483, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyupdi", line 11, in <module>
    load_entry_point('pyupdi==0.0.0', 'console_scripts', 'pyupdi')()
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/pyupdi.py", line 105, in _main
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/nvm.py", line 54, in unlock_device
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/application.py", line 113, in unlock
  File "/usr/local/lib/python3.8/dist-packages/pyupdi-0.0.0-py3.8.egg/updi/application.py", line 142, in _progmode_key
Exception: Key not accepted
base@bananapi:~$ sudo pyupdi -d tiny816 -c /dev/ttyS1 -f /home/base/python.base/sbu_fw_files/BaSe_SBC_wakeup_reason_implementation.hex 
Device info: {'family': 'tinyAVR', 'nvm': 'P:0', 'ocd': 'D:0', 'osc': '3', 'device_id': '1E9321', 'device_rev': '0.1'}
Programming successful
base@bananapi:~$ 

```

**Comment by M-Welsch** [comment]
not reproducible

**Comment by M-Welsch** [comment]
still not reproducible
