### ISSUE TITLE
Mounting HDD with erroneous device info in drive.json crashes the program

### ISSUE THREAD

**Issue by M-Welsch** [M-Welsch/base-bcu#18]
```
Sep 19 20:01:47 bananapi sudo[605]: INFO: BaSe.base.common.file_system: Try to find partition for the first time...
Sep 19 20:02:00 bananapi sudo[605]: DEBUG: BaSe.base.common.file_system: File /dev/sg0 was created
Sep 19 20:02:01 bananapi sudo[605]: INFO: BaSe.base.common.file_system: Try to find partition...
Sep 19 20:02:01 bananapi sudo[605]: DEBUG: BaSe.base.common.file_system: File /dev/bsg was created
Sep 19 20:02:01 bananapi sudo[605]: INFO: BaSe.base.common.file_system: Try to find partition...
Sep 19 20:02:01 bananapi sudo[605]: DEBUG: BaSe.base.common.file_system: File /dev/sda was created
Sep 19 20:02:02 bananapi sudo[605]: INFO: BaSe.base.common.file_system: Try to find partition...
Sep 19 20:02:02 bananapi sudo[605]: DEBUG: BaSe.base.common.file_system: File /dev/sda1 was created
Sep 19 20:02:02 bananapi sudo[605]: INFO: BaSe.base.common.file_system: Try to find partition...
Sep 19 20:02:22 bananapi sudo[605]: INFO: BaSe.base.common.file_system: Try to find partition for the last time...
Sep 19 20:02:22 bananapi sudo[605]: ERROR: BaSe.base.hardware.drive: Backup HDD not found!
Sep 19 20:02:22 bananapi sudo[605]: Traceback (most recent call last):
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/logic/backup/backup.py", line 59, in on_backup_request
Sep 19 20:02:22 bananapi sudo[605]:     self._run_backup_sequence()
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/logic/backup/backup.py", line 99, in _run_backup_sequence
Sep 19 20:02:22 bananapi sudo[605]:     self.hardware_engage_request.emit()
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/local/lib/python3.8/dist-packages/signalslot/signal.py", line 137, in emit
Sep 19 20:02:22 bananapi sudo[605]:     result = slot(**kwargs)
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/hardware/hardware.py", line 33, in engage
Sep 19 20:02:22 bananapi sudo[605]:     self._drive.mount()
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/hardware/drive.py", line 37, in mount
Sep 19 20:02:22 bananapi sudo[605]:     raise MountingError(f"Backup HDD not available!")
Sep 19 20:02:22 bananapi sudo[605]: base.common.exceptions.MountingError: Backup HDD not available!
Sep 19 20:02:22 bananapi sudo[605]: During handling of the above exception, another exception occurred:
Sep 19 20:02:22 bananapi sudo[605]: Traceback (most recent call last):
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Sep 19 20:02:22 bananapi sudo[605]:     return _run_code(code, main_globals, None,
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Sep 19 20:02:22 bananapi sudo[605]:     exec(code, run_globals)
Sep 19 20:02:22 bananapi sudo[605]:   File "python.base/base/__main__.py", line 36, in <module>
Sep 19 20:02:22 bananapi sudo[605]:     main()
Sep 19 20:02:22 bananapi sudo[605]:   File "python.base/base/__main__.py", line 29, in main
Sep 19 20:02:22 bananapi sudo[605]:     app.start()
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/base_application.py", line 89, in start
Sep 19 20:02:22 bananapi sudo[605]:     self._schedule.run_pending()
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/logic/schedule.py", line 36, in run_pending
Sep 19 20:02:22 bananapi sudo[605]:     self._scheduler.run(blocking=False)
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/lib/python3.8/sched.py", line 151, in run
Sep 19 20:02:22 bananapi sudo[605]:     action(*argument, **kwargs)
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/logic/schedule.py", line 53, in _invoke_backup
Sep 19 20:02:22 bananapi sudo[605]:     self.backup_request.emit()
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/local/lib/python3.8/dist-packages/signalslot/signal.py", line 137, in emit
Sep 19 20:02:22 bananapi sudo[605]:     result = slot(**kwargs)
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/logic/backup/backup.py", line 68, in on_backup_request
Sep 19 20:02:22 bananapi sudo[605]:     LOG.error(e)
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/lib/python3.8/logging/__init__.py", line 1463, in error
Sep 19 20:02:22 bananapi sudo[605]:     self._log(ERROR, msg, args, **kwargs)
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
Sep 19 20:02:22 bananapi sudo[605]:     self.handle(record)
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
Sep 19 20:02:22 bananapi sudo[605]:     self.callHandlers(record)
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
Sep 19 20:02:22 bananapi sudo[605]:     hdlr.handle(record)
Sep 19 20:02:22 bananapi sudo[605]:   File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
Sep 19 20:02:22 bananapi sudo[605]:     self.emit(record)
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/common/logger.py", line 31, in emit
Sep 19 20:02:22 bananapi sudo[605]:     self._message_cache.push(record.msg)
Sep 19 20:02:22 bananapi sudo[605]:   File "/home/base/python.base/base/common/logger.py", line 15, in push
Sep 19 20:02:22 bananapi sudo[605]:     raise ValueError(f"Item has to be of type str, but is of type {type(item)}")
Sep 19 20:02:22 bananapi sudo[605]: ValueError: Item has to be of type str, but is of type <class 'base.common.exceptions.MountingError'>
```

**Comment by M-Welsch** [comment]
invalid since udev does this job now
