### ISSUE TITLE
Using UART may fail

### ISSUE THREAD

**Issue by M-Welsch** [M-Welsch/base-bcu#20]
cfa4903 (HEAD -> testing/unit_tests, origin/testing/unit_tests) refactor syncstatus to dataclass add stub for test_parse_line_to_status

```
sudo python3 python.base/utils/control_hardware.py -u
INFO: BaSe.base.common.config: reloading config: /home/base/python.base/base/config/sync.json
INFO: BaSe.base.common.config: reloading config: /home/base/python.base/base/config/hardware.json
INFO: BaSe.base.common.config: reloading config: /home/base/python.base/base/config/mechanics.json
INFO: BaSe.base.common.config: reloading config: /home/base/python.base/base/config/sbu.json
DEBUG: BaSe.base.hardware.sbu.sbu_uart_finder: interface: /dev/ttyS2, response: b''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 500, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python.base/utils/control_hardware.py", line 53, in <module>
    control_hardware()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "python.base/utils/control_hardware.py", line 24, in control_hardware
    hardware = Hardware(backup_browser=BackupBrowser())
  File "/home/base/python.base/base/hardware/hardware.py", line 23, in __init__
    self._sbu: SBU = SBU()
  File "/home/base/python.base/base/hardware/sbu/sbu.py", line 24, in __init__
    self._sbu_communicator = SbuCommunicator()
  File "/home/base/python.base/base/hardware/sbu/sbu_communicator.py", line 20, in __init__
    self._sbu_uart_interface = self._get_uart_interface()
  File "/home/base/python.base/base/hardware/sbu/sbu_communicator.py", line 25, in _get_uart_interface
    return SbuUartFinder().get_sbu_uart_interface()
  File "/home/base/python.base/base/hardware/sbu/sbu_uart_finder.py", line 14, in get_sbu_uart_interface
    uart_sbu = self._test_uart_interfaces_for_echo(uart_interfaces)
  File "/home/base/python.base/base/hardware/sbu/sbu_uart_finder.py", line 24, in _test_uart_interfaces_for_echo
    if self._test_uart_interface_for_echo(uart_interface):
  File "/home/base/python.base/base/hardware/sbu/sbu_uart_finder.py", line 31, in _test_uart_interface_for_echo
    response = SbuUartFinder._challenge_interface(uart_interface)
  File "/home/base/python.base/base/hardware/sbu/sbu_uart_finder.py", line 44, in _challenge_interface
    response: bytes = ser.serial_connection.read_until(b"Echo")
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 659, in read_until
    c = self.read(1)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

**Comment by M-Welsch** [comment]
not reproducible
